
name: BATS
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test-linux:
    strategy:
      matrix:
        os: ['ubuntu-20.04', 'ubuntu-22.04']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.8.2
      - name: Setup BATS libs
        uses: brokenpip3/setup-bats-libs@0.1.0
        with:
          file-install: false
      - name: Fetch bats-file sub-module
        run: git fetch 'test/test_helper/bats-file'
      - name: Tests
        run: bats -r 'test/'
