name: tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: 'macos-latest'
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Tests
        run: sudo --user='runner' make test  
  coverage:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - name: Tests & Coverage
        run: sudo --user='runner' --preserve-env='PATH' make coverage
      - name: Codecov.io
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/codecov-result.json
          flags: unittests
          name: biapy-bashling
          fail_ci_if_error: false
          verbose: false # optional (default = false)
