name: Makefile actions
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  # format:
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - name: Clone repository
  #       uses: actions/checkout@v3
  #     - name: Update apt available packages list.
  #       run: sudo apt-get update
  #     - name: Install requirements
  #       run: sudo apt-get install -y 'make' 'shfmt'
  #     - name: Run 'format' Makefile action.
  #       run: make format
  # check:
  #   needs: format
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - name: Clone repository
  #       uses: actions/checkout@v3
  #     - name: Update apt available packages list.
  #       run: sudo apt-get update
  #     - name: Install requirements
  #       run: sudo apt-get install -y 'make' 'shellcheck'
  #     - name: Run 'check' Makefile action.
  #       run: make check
  test:
    # needs: check
    name: Run tests
    runs-on: ubuntu-22.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Clone submodules
        run: git submodule update --recursive --init
      - name: Run tests
        run: make test
