name: test
on: [push, pull_request]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run format Makefile action.
        run: |
          sudo apt-get update -y
          sudo apt-get install 'format' 'make'
          make format
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run check Makefile action.
        run: |
          sudo apt-get update -y
          sudo apt-get install 'shellcheck' 'make'
          make check
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v1
      - name: Clone submodules
        run: git submodule update --recursive --init
      - name: Run tests
        run: make test
