name: test
on: [push, pull_request]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Update apt available packages list.
        run: sudo apt-get update
      - name: Install requirements
        run: sudo apt-get install -y 'make' 'shfmt'
      - name: Run 'format' Makefile action.
        run: make format
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Update apt available packages list.
        run: sudo apt-get update
      - name: Install requirements
        run: sudo apt-get install -y 'make' 'shellcheck'
      - name: Run 'check' Makefile action.
        run: make check
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Clone submodules
        run: git submodule update --recursive --init
      - name: Run tests
        run: make test
